### ISSUE TITLE
IE10: Unable to get property 'length' of undefined or null reference

### ISSUE THREAD

**Issue by dgsunesen** [taunus/taunus#10]
When starting taunus in IE10, I get this error in router.js..

line 11:
```var base = location.href.substr(location.origin.length);```

**Comment by bevacqua** [comment]
Thank you so much, I've been meaning to test Taunus under IE9+. We should either:

- Polyfill `location.origin`

```
if (!location.origin) {
  location.origin = location.protocol + "//" + location.hostname + (location.port ? ':' + location.port: '');
}
```

- Just use `location.origin` as in the snippet above, but without changing `location.origin`. I'm inclined towards the second use case, as it's less unpredictable (least surprise principle)

```
var origin = location.origin || (location.protocol + "//" + location.hostname + (location.port ? ':' + location.port: ''));
var base = location.href.substr(origin.length);
```

If you agree, could you create a PR with this change? Otherwise I'll update when I can

**Comment by dgsunesen** [comment]
Totally agree. And thanks so much for being so fast on solving these issues! :) Big hi-five!
